// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// If you need to export a config, you can use a plain object or adjust the import to a valid Prisma integration package.
// For most setups, Prisma uses `prisma/schema.prisma` and CLI commands, not a TypeScript config file.
// If you have a custom integration, replace the import with the correct package, e.g.:
// import { defineConfig } from "@prisma/integration"; // (if such a package exists)

// Example: Exporting config as a plain object (optional)
export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
